import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import test from 'node:test';

const root = path.resolve(import.meta.dirname, '..', '..');
const generator = path.join(root, 'scripts', 'release', 'generate-k4d-claude-plugin.mjs');
const validator = path.join(root, 'scripts', 'release', 'validate-k4d-claude-plugin.mjs');
const transcriptFixture = path.join(root, 'tests', 'fixtures', 'release', 'k4d-plugin-validate-transcripts-v1.json');

function run(command, args, options = {}) {
  return spawnSync(command, args, { encoding: 'utf8', ...options });
}

function parseReceipt(stdout) {
  const start = stdout.indexOf('{');
  assert.notEqual(start, -1, stdout);
  return JSON.parse(stdout.slice(start));
}

function sha256(bytes) {
  return createHash('sha256').update(bytes).digest('hex');
}

async function build(prefix = 'ks77-manifest-validation-') {
  const dir = await mkdtemp(path.join(tmpdir(), prefix));
  const result = run(process.execPath, [generator, '--out', dir], { cwd: root });
  assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
  return { dir, receipt: parseReceipt(result.stdout) };
}

// The validator always writes its receipt (even in dry-run), so every call targets a
// throwaway path inside the temp dir to keep the committed receipt untouched.
async function validate(dir, extra = []) {
  const receiptPath = path.join(await mkdtemp(path.join(tmpdir(), 'ks77-manifest-receipt-')), 'receipt.json');
  return run(process.execPath, [validator, '--fixture', transcriptFixture, '--out', dir, '--dry-run', '--receipt', receiptPath, ...extra], { cwd: root });
}

async function writeTranscriptVariant(prefix, mutate) {
  const dir = await mkdtemp(path.join(tmpdir(), prefix));
  const fixture = JSON.parse(await readFile(transcriptFixture, 'utf8'));
  mutate(fixture);
  const file = path.join(dir, 'transcript.json');
  await writeFile(file, `${JSON.stringify(fixture, null, 2)}\n`);
  return { dir, file };
}

function assertDenied(result, pattern) {
  assert.notEqual(result.status, 0, `${result.stdout}\n${result.stderr}`);
  assert.match(result.stderr, pattern);
}

test('accepts a generated manifest through the recorded Claude Code plugin validation route', async () => {
  const { dir, receipt: generated } = await build();
  const result = await validate(dir);
  assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
  const receipt = parseReceipt(result.stdout);

  assert.equal(receipt.schemaVersion, 'kaleidosphere/k4d-manifest-validation-receipt/v1');
  assert.equal(receipt.canonicalVerification.route, 'repository-generator');
  assert.equal(receipt.canonicalVerification.status, 'passed');
  assert.equal(receipt.canonicalVerification.receiptSchemaVersion, 'kaleidosphere/k4d-claude-plugin-receipt/v1');
  assert.equal(receipt.claudeSchemaValidation.adapter, 'claude-code-plugin-validate');
  assert.equal(receipt.claudeSchemaValidation.toolVersion, '2.1.259');
  assert.equal(receipt.claudeSchemaValidation.report.success, true);
  assert.equal(receipt.claudeSchemaValidation.report.strict, true);
  assert.equal(receipt.claudeSchemaValidation.report.manifest.type, 'plugin');
  assert.equal(receipt.claudeSchemaValidation.report.manifest.errors.length, 0);
  assert.equal(receipt.claudeSchemaValidation.report.contents.length, 0);
  assert.equal(receipt.packageDigest, generated.packageDigest);
  assert.match(receipt.packageDigest, /^[a-f0-9]{64}$/);
  assert.equal(receipt.manifest.sha256, 'b8a53a99c90b10982ca7cd15291d000291dc6a0e511b6b6ff53b2222741ae42d');
  assert.ok(['LIVE_VALIDATOR', 'RECORDED_TRANSCRIPT_DRY_RUN'].includes(receipt.claudeSchemaValidation.execution));
  assert.equal(receipt.publicationPerformed, false);
  assert.equal(receipt.accepted, true);
});

test('acceptance cannot bypass canonical verification when generated bytes are stale', async () => {
  const { dir } = await build('ks77-manifest-stale-');
  const skill = path.join(dir, 'skills', 'kaleidosphere', 'SKILL.md');
  await writeFile(skill, `${await readFile(skill, 'utf8')}\nstale generated digest\n`);
  assertDenied(await validate(dir), /repository generator validation denied|changed generated byte denied/);
});

test('missing manifest field is denied before plugin acceptance', async () => {
  const { dir } = await build('ks77-manifest-missing-');
  const manifestPath = path.join(dir, '.claude-plugin', 'plugin.json');
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
  delete manifest.description;
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  assertDenied(await validate(dir), /repository generator validation denied|plugin manifest drift denied/);
});

test('unknown skill path is denied before plugin acceptance', async () => {
  const { dir } = await build('ks77-manifest-unknown-skill-');
  const manifestPath = path.join(dir, '.claude-plugin', 'plugin.json');
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
  manifest.skills = './unknown/';
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  assertDenied(await validate(dir), /repository generator validation denied|plugin manifest skills path drift denied/);
});

test('transcript fixture schema drift is fail-closed before any validation', async () => {
  const { dir } = await build('ks77-manifest-schema-drift-');
  const variant = await writeTranscriptVariant('ks77-transcript-schema-drift-', (fixture) => {
    fixture.schemaVersion = 'wrong';
  });
  const result = await validate(dir, ['--fixture', variant.file]);
  assertDenied(result, /plugin-validate transcript fixture schema drift denied/);
});

test('unknown argument is fail-closed', async () => {
  const { dir } = await build('ks77-manifest-unknown-arg-');
  const result = await validate(dir, ['--bogus']);
  assertDenied(result, /unknown argument: --bogus/);
});