import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { chmod, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import test from 'node:test';

const root = path.resolve(import.meta.dirname, '..', '..');
const generator = path.join(root, 'scripts', 'release', 'generate-k4c-codex-plugin.mjs');
const validator = path.join(root, 'scripts', 'release', 'validate-k4c-codex-plugin.mjs');
const transcriptFixture = path.join(root, 'tests', 'fixtures', 'release', 'k4c-plugin-creator-transcripts-v1.json');

function run(command, args, options = {}) {
  return spawnSync(command, args, { encoding: 'utf8', ...options });
}

function parseReceipt(stdout) {
  const start = stdout.indexOf('{');
  assert.notEqual(start, -1, stdout);
  return JSON.parse(stdout.slice(start));
}

function sha256(bytes) {
  return createHash('sha256').update(bytes).digest('hex');
}

async function build(prefix = 'ks76-manifest-validation-') {
  const dir = await mkdtemp(path.join(tmpdir(), prefix));
  const result = run(process.execPath, [generator, '--out', dir], { cwd: root });
  assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
  return { dir, receipt: parseReceipt(result.stdout) };
}

function validate(dir, extra = []) {
  return run(process.execPath, [validator, '--fixture', transcriptFixture, '--out', dir, '--dry-run', ...extra], { cwd: root });
}

async function writeTranscriptVariant(prefix, mutate) {
  const dir = await mkdtemp(path.join(tmpdir(), prefix));
  const fixture = JSON.parse(await readFile(transcriptFixture, 'utf8'));
  mutate(fixture);
  const file = path.join(dir, 'transcript.json');
  await writeFile(file, `${JSON.stringify(fixture, null, 2)}\n`);
  return { dir, file };
}

function assertDenied(result, pattern) {
  assert.notEqual(result.status, 0, `${result.stdout}\n${result.stderr}`);
  assert.match(result.stderr, pattern);
}

test('accepts a generated manifest through both deterministic validation routes', async () => {
  const { dir, receipt: generated } = await build();
  const result = validate(dir);
  assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
  const receipt = parseReceipt(result.stdout);

  assert.equal(receipt.schemaVersion, 'kaleidosphere/k4c-manifest-validation-receipt/v1');
  assert.equal(receipt.canonicalVerification.status, 'passed');
  assert.equal(receipt.canonicalVerification.receiptSchemaVersion, 'kaleidosphere/k4c-codex-plugin-receipt/v1');
  assert.equal(receipt.pluginCreatorVerification.adapter, '@plugin-creator');
  assert.equal(receipt.pluginCreatorVerification.toolVersion, 'plugin-creator-validator/unversioned-source-recorded');
  assert.equal(receipt.pluginCreatorVerification.validatorSha256, 'ebda00d55d7518b127f675f062fb5c6e7a1ffdc0a99df1a55ac594400d7d3228');
  assert.equal(receipt.packageDigest, generated.packageDigest);
  assert.match(receipt.packageDigest, /^[a-f0-9]{64}$/);
  assert.equal(receipt.manifest.sha256, '64494f3a2e993ba476834dd49dfb1a1a60cfe8671b8ab6f08eb5f86045873b77');
  assert.equal(receipt.pluginCreatorVerification.transcript.exitCode, 0);
  assert.equal(receipt.publicationPerformed, false);
  assert.equal(receipt.accepted, true);
});

test('acceptance cannot bypass canonical verification when generated bytes are stale', async () => {
  const { dir } = await build('ks76-manifest-stale-');
  const skill = path.join(dir, 'skills', 'kaleidosphere', 'SKILL.md');
  await writeFile(skill, `${await readFile(skill, 'utf8')}\nstale generated digest\n`);
  assertDenied(validate(dir), /repository generator validation denied|changed generated byte denied/);
});

test('missing manifest field is denied before plugin-creator acceptance', async () => {
  const { dir } = await build('ks76-manifest-missing-');
  const manifestPath = path.join(dir, '.codex-plugin', 'plugin.json');
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
  delete manifest.interface;
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  assertDenied(validate(dir), /repository generator validation denied|plugin manifest drift denied/);
});

test('unknown skill path is denied before plugin-creator acceptance', async () => {
  const { dir } = await build('ks76-manifest-unknown-skill-');
  const manifestPath = path.join(dir, '.codex-plugin', 'plugin.json');
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
  manifest.skills = './unknown/';
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  assertDenied(validate(dir), /repository generator validation denied|plugin manifest drift denied/);
});

test('validator nonzero result is fail-closed', async () => {
  const { dir } = await build('ks76-manifest-validator-fail-');
  const fake = await mkdtemp(path.join(tmpdir(), 'ks76-fake-plugin-creator-'));
  const fakeValidator = path.join(fake, 'validate_plugin.py');
  const fakeContents = '#!/usr/bin/env python3\nraise SystemExit(7)\n';
  await writeFile(fakeValidator, fakeContents, { mode: 0o755 });
  await chmod(fakeValidator, 0o755);
  const fakeFixture = await writeTranscriptVariant('ks76-transcript-nonzero-', (fixture) => {
    fixture.validator.path = fakeValidator;
    fixture.validator.sha256 = sha256(Buffer.from(fakeContents));
  });
  const result = run(process.execPath, [validator, '--fixture', fakeFixture.file, '--out', dir, '--dry-run', '--validator', fakeValidator], { cwd: root });
  assertDenied(result, /plugin-creator validator nonzero denied: exit 7/);
});

test('unavailable validator is fail-closed with explicit infrastructure evidence', async () => {
  const { dir } = await build('ks76-manifest-validator-missing-');
  const missing = path.join(await mkdtemp(path.join(tmpdir(), 'ks76-missing-plugin-creator-')), 'missing.py');
  assertDenied(validate(dir, ['--validator', missing]), /plugin-creator validator unavailable: infrastructure evidence: ENOENT/);
});
