import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync,writeFileSync,mkdirSync,openSync,closeSync,constants,existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {execFileSync} from 'node:child_process';
import {loadPan549ExistingWorkspaceInputV1,mountExistingPan549K05WorkspaceV1} from '../services/bi-control/src/assistant-foundation/pan549-existing-workspace-composition-v1.mjs';
import {loadPan520StockSourceV1} from '../services/bi-control/src/business-bi/pan520-stock-consumer.mjs';
import {createPan549K05StockReadPairV1} from '../services/bi-control/src/assistant-foundation/pan549-k05-stock-read-pair-v1.mjs';
const sha=raw=>createHash('sha256').update(raw).digest('hex');
const selector={schemaVersion:'pansphaira.workspace-analysis/read/v1',objectId:'analysis:common-trade-01:stock',expectedNativeRevision:null,expectedResultRevision:null,asOf:'2026-06-30T23:59:59+02:00'};
const load=(root,path)=>import(pathToFileURL(join(root,path)).href);

test('KS303 actual unchanged K05 consumer in the existing protected PAN view/panel/chart: source pairing, reversible session, native denials, layout and retirement',async t=>{
 const stage=async(name,fn)=>{let failure;await t.test(name,async()=>{try{await fn();}catch(error){failure=error;throw error;}});if(failure)throw failure;};
 for(const key of ['KS303_PAN549_SOURCE_ROOT','KS303_K05_SOURCE_ROOT','KS303_PLAYWRIGHT_MODULE','KS303_CHROMIUM_EXECUTABLE','KS303_CERTUTIL','KS303_BROWSER_EVIDENCE_DIR','TMPDIR'])assert.ok(process.env[key],'KS303_REQUIRED_REAL_INPUT_NOT_RUN: '+key);
 const pan=process.env.KS303_PAN549_SOURCE_ROOT,evidence=process.env.KS303_BROWSER_EVIDENCE_DIR,oldCwd=process.cwd();mkdirSync(evidence,{recursive:true});process.chdir(pan);
 const {financeFixture}=await load(pan,'tests/pan519/native-fixture.mjs'),{nativeRows}=await load(pan,'tests/fixtures/pan515/native-trade-fixture.mjs'),{nativeFixture527,request527}=await load(pan,'tests/pan527/helpers.mjs');
 const {createNativeAnalysisReadAdapterV1,isNativeAnalysisReadAdapterV1}=await load(pan,'src/pan549/native-analysis-read.mjs');
 let native,tls,workspace,browser,context,page,fd,standalone;
 const receipts={schemaVersion:'kaleidosphere/ks303-actual-existing-shared-workspace-product/v1',atUtc:new Date().toISOString(),sourceScope:'Own permitted synthetic native source only; no model/provider/business/promotion/source rights granted',original303WholeDone:false,originalPANSourceModified:false,secondShell:false,cases:[],screenshots:[]};
 const shot=async(page,name)=>{await page.screenshot({path:join(evidence,name+'.png'),fullPage:true});receipts.screenshots.push({name:name+'.png',sha256:sha(readFileSync(join(evidence,name+'.png'))),viewport:page.viewportSize(),resultRevision:await page.evaluate(()=>document.body.dataset.analysisResultRevision??null),state:await page.evaluate(()=>document.querySelector('[data-backend="analysis"]')?.dataset.outcome??null),contextRevision:await page.evaluate(()=>document.body.dataset.contextRevision??null),ownedKSState:await page.evaluate(()=>document.getElementById('ks303-existing-k05-read-companion')?.dataset.ks303State??null)});};
 const record=(id,values={})=>receipts.cases.push({id,outcome:'PASS',...values});
 try{
  native=await financeFixture();tls=await nativeFixture527();const rows=()=>nativeRows(native.root,'SELECT revision,command,event FROM pan515_events ORDER BY revision');const before=rows();
  const commands=before.map(r=>JSON.parse(r.command)).filter(c=>Date.parse(c.effectiveAt)<=Date.parse(selector.asOf));const expectedPhysical=commands.filter(c=>c.kind==='RECEIPT').reduce((s,c)=>s+c.quantity,0)-commands.filter(c=>c.kind==='SHIP').reduce((s,c)=>s+c.quantity,0);
  const source=await loadPan549ExistingWorkspaceInputV1({sourceRoot:pan}),ksSource=await loadPan520StockSourceV1({sourceRoot:process.env.KS303_K05_SOURCE_ROOT});
  const sessions=tls.gateway.sessionAdapter('tenant-a'),issued=sessions.issueOwnerSession({subjectId:'synthetic:ks303-existing-shared-read-owner',role:'reader',expiresAtMs:Date.now()+300000});const headers={cookie:issued.cookieHeader,origin:tls.origin};
  standalone=createPan549K05StockReadPairV1({ksSource,nativeRoot:native.root,sessions,nativeReader:createNativeAnalysisReadAdapterV1({optIn:true,root:native.root,sessions}),isNativeReader:isNativeAnalysisReadAdapterV1});
  await stage('Actual six facts and independent persisted native source match with distinct KS/PAN revisions',async()=>{
   const result=await standalone.read(headers,selector);const pair=standalone.readPairEvidence();assert.equal(result.rows[0].value,expectedPhysical);assert.equal(pair.sixFactsCompared,true);assert.notEqual(pair.PAN.commit,pair.KSConsumer.producerCommit);assert.equal(pair.PANResultRevision,result.resultRevision);assert.equal(pair.persistentSupersetMutation,false);assert.equal(pair.syntheticOnly,true);assert.deepEqual(rows(),before);receipts.initialActualNativeResult=result;receipts.initialActualPairEvidence=pair;record('REAL_SIX_FACTS_INDEPENDENT_NATIVE_SOURCE_AND_EXPLICIT_DISTINCT_SOURCE_RESULT_IDENTITIES',{independentPhysical:expectedPhysical,pair});
  });
  await stage('Direct no counterpart, copied source authority, unbranded reader, wrong scope/grain/source revision/result revision and metadata authority are denied',async()=>{
   assert.throws(()=>mountExistingPan549K05WorkspaceV1({source:structuredClone(source),ksSource,nativeRoot:native.root,gateway:tls.gateway,tenantId:'tenant-a',origin:tls.origin}),/SOURCE_HANDLE_DENIED/);
   assert.throws(()=>createPan549K05StockReadPairV1({ksSource,nativeRoot:native.root,sessions,nativeReader:{read:()=>receipts.initialActualNativeResult},isNativeReader:isNativeAnalysisReadAdapterV1}),/NATIVE_READER_OWNER_DENIED/);
   const copied=createPan549K05StockReadPairV1({ksSource:structuredClone(ksSource),nativeRoot:native.root,sessions,nativeReader:createNativeAnalysisReadAdapterV1({optIn:true,root:native.root,sessions}),isNativeReader:isNativeAnalysisReadAdapterV1});try{await assert.rejects(copied.read(headers,selector));assert.equal(copied.readPairEvidence(),null);}finally{copied.close();}
   for(const changes of [{objectId:'analysis:foreign:stock'},{expectedNativeRevision:999},{expectedResultRevision:'0'.repeat(64)},{grain:{tenantId:'tenant-b'}},{tenantId:'tenant-b'},{authority:'reviewer'},{url:'https://outside.invalid/frame'},{asOf:'2026-05-31T23:59:59+02:00'}]){await assert.rejects(standalone.read(headers,{...selector,...changes}));assert.equal(standalone.readPairEvidence(),null);}
   await assert.rejects(standalone.read({...headers,origin:'https://outside.invalid'},selector));standalone.close();await assert.rejects(standalone.read(headers,selector),/CLOSED/);assert.deepEqual(rows(),before);record('DIRECT_SOURCE_COPY_MISSING_NATIVE_CAPABILITY_SOURCE_REVISION_RESULT_REVISION_GRAIN_SCOPE_EMBED_AUTHORITY_CUTOFF_ORIGIN_AND_CLOSED_DENIALS');
  });
  workspace=mountExistingPan549K05WorkspaceV1({source,ksSource,nativeRoot:native.root,gateway:tls.gateway,tenantId:'tenant-a',origin:tls.origin});receipts.actualOwnedCompositionBinding=workspace.binding;
  const protectedContext=JSON.parse((await request527(tls,'/t/tenant-a/workspace/context',{cookie:issued.cookieHeader})).body);const httpHeaders={...headers,'x-pan549-context':protectedContext.sessionId};
  await stage('Actual protected ingress denies scope/authority/persistent superset/arbitrary URL and stale/future revisions without effects',async()=>{
   const actual=await request527(tls,'/t/tenant-a/workspace/analysis',httpHeaders,'POST',selector);assert.equal(actual.status,200);assert.equal(actual.tlsAuthorized,true);assert.equal(actual.headers['set-cookie'],undefined);
   const cases=[{change:{tenantId:'tenant-b'},expected:400},{change:{grain:{tenantId:'tenant-b'}},expected:400},{change:{persistentSupersetMutation:true},expected:400},{change:{authority:'reviewer'},expected:400},{change:{url:'https://outside.invalid/iframe'},expected:400},{change:{expectedNativeRevision:999},expected:409},{change:{expectedResultRevision:'0'.repeat(64)},expected:409}];
   for(const c of cases){const reply=await request527(tls,'/t/tenant-a/workspace/analysis',httpHeaders,'POST',{...selector,...c.change});assert.equal(reply.status,c.expected);assert.equal(reply.headers['set-cookie'],undefined);}
   assert.equal((await request527(tls,'/t/tenant-a/workspace/analysis',{cookie:issued.cookieHeader,origin:tls.origin},'POST',selector)).status,401);
   assert.equal((await request527(tls,'/t/tenant-a/workspace/analysis',{...httpHeaders,origin:'https://outside.invalid'},'POST',selector)).status,403);
   assert.equal((await request527(tls,'/t/tenant-b/workspace/analysis',httpHeaders,'POST',selector)).status,401);assert.deepEqual(rows(),before);record('REAL_PROTECTED_INGRESS_SOURCE_SCOPE_GRAIN_AUTHORITY_PERSISTENT_SUPERSET_URL_ORIGIN_SESSION_TENANT_AND_STALE_DENIALS',{directCases:cases});
  });
  const home=join(tls.root,'ks303-owned-real-browser-home'),nss=join(home,'.pki/nssdb');mkdirSync(nss,{recursive:true,mode:0o700});execFileSync(process.env.KS303_CERTUTIL,['-N','--empty-password','-d','sql:'+nss],{stdio:'ignore'});execFileSync(process.env.KS303_CERTUTIL,['-A','-d','sql:'+nss,'-n','KS303 invocation-only synthetic PAN TLS CA','-t','CT,C,C','-i',tls.options.tls.certPath],{stdio:'ignore'});
  fd=openSync(process.env.TMPDIR,constants.O_RDONLY|constants.O_DIRECTORY|constants.O_NOFOLLOW);const browserEnv=Object.fromEntries(['PATH','LANG','LC_ALL','LD_LIBRARY_PATH','PLAYWRIGHT_BROWSERS_PATH'].filter(k=>process.env[k]!==undefined).map(k=>[k,process.env[k]]));browserEnv.HOME=home;browserEnv.TMPDIR='/proc/'+process.pid+'/fd/'+fd;
  const {chromium}=await import(process.env.KS303_PLAYWRIGHT_MODULE);browser=await chromium.launch({headless:true,executablePath:process.env.KS303_CHROMIUM_EXECUTABLE,env:browserEnv,args:['--no-proxy-server','--disable-background-networking']});context=await browser.newContext({ignoreHTTPSErrors:false,viewport:{width:1280,height:900}});await context.route('**/*',r=>new URL(r.request().url()).origin===tls.origin?r.continue():r.abort());await context.addCookies([{name:'__Host-pan527-session',value:issued.cookieHeader.split('=')[1],url:tls.origin,secure:true,httpOnly:true,sameSite:'Strict'}]);
  page=await context.newPage();const requests=[],errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push({method:r.method(),path:new URL(r.url()).pathname}));page.on('response',async r=>{if(new URL(r.url()).pathname.endsWith('/workspace/analysis')&&r.status()===200)results.push(await r.json());});
  await page.goto(tls.origin+'/t/tenant-a/workspace');await page.locator('[data-backend="setup"][data-outcome="READBACK_RECEIVED"]').waitFor();
  const analysis=page.getByRole('button',{name:'Gebundene Bestandsanalyse — nur lesen',exact:true}),setup=page.getByRole('button',{name:'Einrichtung und Betriebszustand',exact:true});
  const currentCompanion=()=>page.locator('#ks303-existing-k05-read-companion[data-ks303-state="CURRENT"]');
  const terminalProof=async state=>{
   const section=page.locator('#ks303-existing-k05-read-companion[data-ks303-state="'+state+'"]');await section.waitFor();
   const actual=await section.evaluate(e=>({state:e.dataset.ks303State,oldAttributes:['data-ks303-result-revision','data-ks303-session','data-ks303-session-action'].filter(k=>e.hasAttribute(k)),statusText:e.querySelector('[role="status"]')?.textContent??null}));
   assert.deepEqual(actual.oldAttributes,[]);assert.ok(actual.statusText?.includes(state));assert.match(actual.statusText,{STALE:/Revision veraltet/,UNAVAILABLE:/Quelle nicht verfügbar/,DENIED:/Zugriff verweigert/,UNKNOWN:/Readback unbekannt/}[state]);return actual;
  };
  const tableReach=async label=>{
   await page.locator('.analysis-table-scroll').focus();const seen=new Set(),coverage=new Map();let actual;
   await page.locator('.analysis-table-scroll thead').scrollIntoViewIfNeeded();
   for(let n=0;n<160&&await page.locator('.analysis-table-scroll').evaluate(e=>e.scrollLeft)>1;n++){await page.keyboard.press('ArrowLeft');await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}
   assert.ok(await page.locator('.analysis-table-scroll').evaluate(e=>e.scrollLeft)<=1,label+' actual keyboard reaches left edge before scanning');
   for(let n=0;n<160;n++){
    actual=await page.locator('.analysis-table-scroll').evaluate(e=>{const box=e.getBoundingClientRect();return {scrollLeft:e.scrollLeft,clientWidth:e.clientWidth,scrollWidth:e.scrollWidth,viewport:{width:innerWidth,height:innerHeight},columns:[...e.querySelectorAll('thead th,tbody tr:first-child td')].map(h=>{const range=document.createRange();range.selectNodeContents(h);const r=range.getBoundingClientRect(),node=document.createTreeWalker(h,NodeFilter.SHOW_TEXT).nextNode(),visibleCharacters=[];if(!node||node.textContent!==h.textContent)throw new Error('KS303_TABLE_TEXT_PREMISE_REQUIRED');for(let i=0;i<node.textContent.length;i++){range.setStart(node,i);range.setEnd(node,i+1);const glyph=range.getBoundingClientRect();if(glyph.left>=Math.max(0,box.left)-2&&glyph.right<=Math.min(innerWidth,box.right)+2&&glyph.top>=0&&glyph.bottom<=innerHeight)visibleCharacters.push(i);}return {text:h.textContent,textBounds:r.toJSON(),visibleCharacters};}),firstRowValues:[...e.querySelectorAll('tbody tr:first-child td')].map(c=>c.textContent)};});
    for(const c of actual.columns){if(!coverage.has(c.text))coverage.set(c.text,new Set());c.visibleCharacters.forEach(i=>coverage.get(c.text).add(i));if(coverage.get(c.text).size===c.text.length)seen.add(c.text);}if(actual.scrollLeft+actual.clientWidth>=actual.scrollWidth-2)break;
    await page.keyboard.press('ArrowRight');await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
   }
   assert.ok(actual.scrollLeft+actual.clientWidth>=actual.scrollWidth-2,label+' actual keyboard reaches right edge');assert.deepEqual([...seen].sort(),actual.columns.map(c=>c.text).sort(),label+' every original table column actually exposed');
   return {label,actualKeyboardScroll:true,nativePresentationScrollIntoView:true,completeHeaderAndActualFirstRowTextSeenInViewportOverActualScroll:true,wideColumnSimultaneousFitNotClaimed:true,seenColumnsAndFirstRowText:[...seen],rightEdge:actual};
  };
  // CDP withholds an ACTUAL TLS backend response, without replacing bytes,
  // HTTP status, headers, producer code, fetch, crypto or DOM context markers.
  const pauseResponses=async()=>{
   const cdp=await context.newCDPSession(page),waiting=[],buffer=[];
   cdp.on('Fetch.requestPaused',e=>{if(waiting.length)waiting.shift()(e);else buffer.push(e);});
   await cdp.send('Fetch.enable',{patterns:[{urlPattern:tls.origin+'/t/tenant-a/workspace/analysis',requestStage:'Response'}]});
   return {next:()=>buffer.length?Promise.resolve(buffer.shift()):new Promise(r=>waiting.push(r)),async bytes(e){assert.equal(e.responseStatusCode,200);const raw=await cdp.send('Fetch.getResponseBody',{requestId:e.requestId});const body=Buffer.from(raw.body,raw.base64Encoded?'base64':'utf8');const v=JSON.parse(body);assert.equal(v.rows[0].value,expectedPhysical);return {responseStatus:200,actualNativeResponseSHA256:sha(body),resultRevision:v.resultRevision};},release:e=>cdp.send('Fetch.continueResponse',{requestId:e.requestId}),async close(){await cdp.send('Fetch.disable');await cdp.detach();}};
  };
  await stage('Actual shared native shell keyboard action, observed real backend read, verified table and chart are one current bounded result',async()=>{
   const paused=await pauseResponses();try{
    await analysis.focus();await page.keyboard.press('Enter');const nativeLoading=await paused.next();const loading=await paused.bytes(nativeLoading);await page.locator('[data-backend="analysis"][data-outcome="LOADING"]').waitFor();assert.equal(await page.locator('[data-analysis-value]').count(),0);await shot(page,'ks303-desktop-actual-loading');await page.setViewportSize({width:390,height:844});await shot(page,'ks303-390-actual-loading');await paused.release(nativeLoading);
    const pairChecking=await paused.next();const checking=await paused.bytes(pairChecking);await page.locator('#ks303-existing-k05-read-companion[data-ks303-state="CHECKING"]').waitFor();const checkingStatus=await page.locator('#ks303-existing-k05-read-companion [role="status"]').innerText();assert.match(checkingStatus,/Prüfe Quelle/);assert.equal(await page.locator('[data-ks303-chart]').count(),0);await shot(page,'ks303-390-actual-k05-checking');await paused.release(pairChecking);await currentCompanion().waitFor();record('ACTUAL_BROWSER_LOADING_AND_CHECKING_WITH_UNALTERED_HELD_NATIVE_RESPONSES',{loading,checking,companionStatusSemantics:{role:'status',text:checkingStatus,screenReaderSpeechNotClaimed:true}});
   }finally{await paused.close();}
   await page.setViewportSize({width:1280,height:900});await page.locator('[data-backend="analysis"][data-outcome="READBACK_RECEIVED"]').waitFor();await currentCompanion().waitFor();const actual=results.at(-1),pair=workspace.readPairEvidence();assert.ok(actual);assert.equal(pair.PANResultRevision,actual.resultRevision);assert.equal(actual.rows[0].value,expectedPhysical);assert.equal(await page.locator('tr[data-analysis-key="physical"] [data-analysis-value]').innerText(),String(expectedPhysical));assert.equal(await currentCompanion().getAttribute('data-ks303-result-revision'),actual.resultRevision);
   for(const row of actual.rows){assert.equal(await page.locator('tr[data-analysis-key="'+row.key+'"] [data-analysis-value]').innerText(),row.state==='KNOWN'?String(row.value):'Nicht verfügbar');const mark=page.locator('[data-ks303-key="'+row.key+'"]');assert.equal(await mark.count(),row.state==='KNOWN'&&row.unit==='STK'?1:0);if(await mark.count()){assert.equal(await mark.getAttribute('data-ks303-value'),String(row.value));assert.equal(await mark.getAttribute('data-ks303-unit'),row.unit);}}
   assert.equal(await page.locator('[data-ks303-chart]').getAttribute('data-result-revision'),actual.resultRevision);assert.equal(await page.locator('iframe').count(),0);assert.equal(await page.evaluate(()=>document.cookie),'');assert.equal(await page.evaluate(()=>window.isSecureContext),true);assert.ok(requests.filter(r=>r.method==='POST'&&r.path==='/t/tenant-a/workspace/analysis').length>=2);assert.deepEqual(rows(),before);await shot(page,'ks303-desktop-current-table-chart');record('REAL_SAME_NATIVE_PAN_SHELL_K05_TABLE_CHART_CONTEXT_SOURCE_UNITS_AND_MISSING_FACTS',{resultRevision:actual.resultRevision,independentPhysical:expectedPhysical,pair});
  });
  await stage('Panel opening, closing and session undo reauthorize actual paired reads; identities explicit; persistent native event revision unchanged',async()=>{
   const show=page.getByRole('button',{name:'Quell- und Pairidentitäten anzeigen',exact:true}),hide=page.getByRole('button',{name:'Identitätspanel schließen',exact:true}),undo=page.getByRole('button',{name:'Sessionansicht zurücknehmen',exact:true});const prior=requests.length;
   const paused=await pauseResponses();try{await show.focus();await page.keyboard.press('Enter');const held=await paused.next();assert.equal(await show.evaluate(e=>document.activeElement===e),true);assert.equal(await show.getAttribute('aria-disabled'),'true');assert.equal(await currentCompanion().getAttribute('aria-busy'),'true');assert.equal(await page.locator('[data-ks303-panel-contract]').isVisible(),false);await page.keyboard.press('Enter');await paused.bytes(held);await paused.release(held);await page.locator('#ks303-existing-k05-read-companion[data-ks303-session-action="SHOW"]').waitFor();}finally{await paused.close();}
   const panel=page.locator('[data-ks303-panel-contract]');assert.equal(await hide.evaluate(e=>document.activeElement===e),true);assert.equal(await show.getAttribute('aria-expanded'),'true');assert.equal(await show.getAttribute('aria-controls'),await panel.getAttribute('id'));assert.equal(await panel.isVisible(),true);assert.equal(await panel.getAttribute('data-ks303-result-revision'),await currentCompanion().getAttribute('data-ks303-result-revision'));assert.match(await panel.innerText(),/fd1fcf3b0392a7069169b7459c8ff8923466f38b/);assert.match(await panel.innerText(),/cf199bbd35706bdeadb04679af7354c94caf482a/);await shot(page,'ks303-desktop-open-identity-panel');
   await hide.focus();await page.keyboard.press('Enter');await page.locator('#ks303-existing-k05-read-companion[data-ks303-session-action="HIDE"]').waitFor();assert.equal(await panel.isVisible(),false);assert.equal(await show.evaluate(e=>document.activeElement===e),true);assert.equal(await show.getAttribute('aria-expanded'),'false');await undo.focus();await page.keyboard.press('Enter');await page.locator('#ks303-existing-k05-read-companion[data-ks303-session-action="UNDO"]').waitFor();assert.equal(await hide.evaluate(e=>document.activeElement===e),true);assert.equal(await panel.isVisible(),true);assert.equal(await undo.isEnabled(),false);assert.match(await panel.innerText(),/PAN-Resultatrevision/);assert.doesNotMatch(await panel.innerText(),/KS\/PAN-Paarrevision/);assert.ok(requests.slice(prior).filter(r=>r.method==='POST'&&r.path==='/t/tenant-a/workspace/analysis').length===3);assert.equal(requests.some(r=>r.method==='PUT'||r.method==='PATCH'||/\/persist|\/approval|\/guided\/command/.test(r.path)),false);assert.deepEqual(rows(),before);record('REAL_REAUTHORIZED_COMMON_CONTEXT_PANEL_OPEN_CLOSE_SESSION_UNDO_NO_PERSISTENT_MUTATION');
  });
  await stage('Actual 390px long German identities, positive DOM/control bounds and focusable local table/chart; real 200 percent CSS zoom',async()=>{
   await page.setViewportSize({width:390,height:844});await shot(page,'ks303-390-current-open-panel');
   const measure=()=>page.evaluate(()=>({viewport:innerWidth,width:document.documentElement.scrollWidth,controls:[...document.querySelectorAll('button:not(:disabled),a,[tabindex="0"]')].filter(e=>e.getClientRects().length).map(e=>{const r=e.getBoundingClientRect();return {label:e.getAttribute('aria-label')??e.textContent,x:r.x,right:r.right,width:r.width,height:r.height};}),table:document.querySelector('.analysis-table-scroll')?.getBoundingClientRect().toJSON(),chart:document.querySelector('[data-ks303-chart]')?.getBoundingClientRect().toJSON(),panel:document.querySelector('[data-ks303-panel-contract]')?.getBoundingClientRect().toJSON()}));
   const mobile=await measure(),fonts=await page.locator('.ks303-bars p').evaluateAll(es=>es.map(e=>({text:e.textContent,fontSize:parseFloat(getComputedStyle(e).fontSize),bounds:e.getBoundingClientRect().toJSON()})));assert.equal(fonts.length,4);assert.ok(fonts.every(f=>f.fontSize>=16&&f.bounds.height>0&&f.bounds.x>=0&&f.bounds.right<=390));assert.ok(mobile.width<=mobile.viewport);for(const rect of [mobile.table,mobile.chart,mobile.panel])assert.ok(rect.width>0&&rect.height>0&&rect.x>=0&&rect.right<=390);assert.ok(mobile.controls.every(r=>r.width>0&&r.height>0&&r.x>=0&&r.right<=390));await page.locator('.analysis-table-scroll').focus();assert.equal(await page.evaluate(()=>document.activeElement?.className),'analysis-table-scroll');await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement?.hasAttribute('data-ks303-chart')),true);
   const mobileTableReach=await tableReach('390 normal');await page.evaluate(()=>document.documentElement.style.zoom='2');const mobileZoomTableReach=await tableReach('390 CSS200');await page.evaluate(()=>document.documentElement.style.zoom='1');
   await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>document.documentElement.style.zoom='2');await shot(page,'ks303-desktop-css-zoom200-open-panel');const zoom=await measure();assert.ok(zoom.controls.every(r=>r.width>0&&r.height>0&&r.x>=0&&r.right<=1280));await page.evaluate(()=>document.documentElement.style.zoom='1');record('REAL_390_LONG_TEXT_ALL_COMPONENT_CONTROL_GEOMETRY_TABLE_AND_CHART_KEYBOARD_CSS_ZOOM200',{mobile,zoom,LOCAL_TABLE_SCROLL_390_CSS200_ALL_COLUMNS:[mobileTableReach,mobileZoomTableReach],zoomScope:'Actual CSS 200 percent layout; not a false native browser-UI zoom claim'});
  });
  await stage('Native view/context retirement removes owned companion and preserves setup; no orphaned chart/panel survives navigation',async()=>{
   await setup.click();await page.locator('[data-backend="setup"][data-outcome="READBACK_RECEIVED"]').waitFor();assert.equal(await page.locator('#ks303-existing-k05-read-companion').count(),0);assert.equal(await page.locator('[data-ks303-chart]').count(),0);assert.equal(await page.evaluate(()=>document.body.dataset.analysisResultRevision??null),null);await analysis.click();await currentCompanion().waitFor();assert.deepEqual(rows(),before);record('REAL_COMMON_NATIVE_VIEW_CONTEXT_RETIREMENT_OWNED_CLEANUP_AND_OTHER_MODULE_PRESERVED');
  });
  await stage('Held actual native panel success cannot overwrite another live module after route/context retirement',async()=>{
   const paused=await pauseResponses();try{await page.getByRole('button',{name:'Quell- und Pairidentitäten anzeigen',exact:true}).click();const held=await paused.next(),actual=await paused.bytes(held);await setup.click();await page.locator('[data-backend="setup"][data-outcome="READBACK_RECEIVED"]').waitFor();const text=await page.locator('main').innerText(),revision=await page.evaluate(()=>document.body.dataset.contextRevision);let release='CONTINUED_UNALTERED_NATIVE_RESPONSE';try{await paused.release(held);}catch{release='NATIVE_RESPONSE_ALREADY_CANCELED_BY_REAL_CONTEXT_RETIREMENT';}await paused.close();assert.equal(await page.locator('main').innerText(),text);assert.equal(await page.evaluate(()=>document.body.dataset.contextRevision),revision);assert.equal(await page.locator('#ks303-existing-k05-read-companion').count(),0);assert.equal(await page.locator('[data-analysis-value]').count(),0);assert.equal(await page.evaluate(()=>document.body.dataset.analysisResultRevision??null),null);assert.deepEqual(rows(),before);record('ACTUAL_HELD_NATIVE_SUCCESS_LATE_AFTER_REAL_ROUTE_CONTEXT_RETIREMENT_OTHER_MODULE_UNCHANGED',{actual,release,revision});}finally{await paused.close().catch(()=>{});}await analysis.click();await currentCompanion().waitFor();
  });
  for(const [state,query,transportFailure] of [['STALE','?objectId=analysis%3Acommon-trade-01%3Astock&revision=999',false],['UNAVAILABLE','',false],['UNKNOWN','',true]]){
   await stage('Actual native browser terminal '+state+' has no old values or claimed counterpart PASS',async()=>{
    await setup.click();await page.locator('[data-backend="setup"][data-outcome="READBACK_RECEIVED"]').waitFor();const url=tls.origin+'/t/tenant-a/workspace/analysis';if(state==='UNAVAILABLE'){workspace.retireAnalysis();assert.equal(workspace.readPairEvidence(),null);assert.equal((await request527(tls,'/t/tenant-a/workspace/analysis',httpHeaders,'POST',selector)).status,404);}if(transportFailure)await page.route(url,r=>r.abort('connectionfailed'));
    try{await page.goto(tls.origin+'/t/tenant-a/workspace#/workspace/analysis'+query);await page.locator('[data-backend="analysis"][data-outcome="'+state+'"]').waitFor();assert.equal(await page.locator('[data-analysis-value],[data-ks303-chart],[data-ks303-panel-contract]').count(),0);assert.equal(await page.evaluate(()=>document.body.dataset.analysisResultRevision??null),null);const terminal=await terminalProof(state);await shot(page,'ks303-desktop-actual-'+state.toLowerCase());await page.setViewportSize({width:390,height:844});await shot(page,'ks303-390-actual-'+state.toLowerCase());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(rows(),before);record('ACTUAL_NATIVE_BROWSER_'+state+'_NO_STALE_VALUES',{query,terminal,actualCounterpartRetired:state==='UNAVAILABLE',transportFailureIsRealRequestAbortNotFabricatedResponse:transportFailure});}finally{if(transportFailure)await page.unroute(url);if(state==='UNAVAILABLE'){workspace.close();workspace=mountExistingPan549K05WorkspaceV1({source,ksSource,nativeRoot:native.root,gateway:tls.gateway,tenantId:'tenant-a',origin:tls.origin});}}await page.setViewportSize({width:1280,height:900});await setup.click();await analysis.click();await currentCompanion().waitFor();
   });
  }
  const cookie=value=>context.addCookies([{name:'__Host-pan527-session',value:value.split('=')[1],url:tls.origin,secure:true,httpOnly:true,sameSite:'Strict'}]);
  await stage('Actual native response held across real protected session change retires old table, panel and success marker',async()=>{
   const paused=await pauseResponses();try{await page.getByRole('button',{name:'Quell- und Pairidentitäten anzeigen',exact:true}).click();const held=await paused.next(),actual=await paused.bytes(held);const switched=sessions.issueOwnerSession({subjectId:'synthetic:ks303-actual-session-switch',role:'reader',expiresAtMs:Date.now()+300000});await cookie(switched.cookieHeader);await paused.release(held);await page.locator('#ks303-existing-k05-read-companion[data-ks303-state="STALE"]').waitFor();assert.match(await page.locator('#ks303-existing-k05-read-companion').innerText(),/STALE.*Revision veraltet/);assert.equal(await page.locator('[data-backend="analysis"]').getAttribute('data-outcome'),'STALE');assert.equal(await page.locator('[data-analysis-value],[data-ks303-chart],[data-ks303-panel-contract]').count(),0);assert.equal(await page.evaluate(()=>document.body.dataset.analysisResultRevision??null),null);await shot(page,'ks303-desktop-real-session-change-stale');await page.setViewportSize({width:390,height:844});await shot(page,'ks303-390-real-session-change-stale');assert.deepEqual(rows(),before);record('ACTUAL_HELD_NATIVE_RESPONSE_SESSION_CHANGE_WITHDRAWN_MARKER_AND_NO_OLD_VALUES',{actual,TERMINAL_OWN_BINDING_MARKERS_WITHDRAWN:await terminalProof('STALE')});}finally{await paused.close();await cookie(issued.cookieHeader);}await page.setViewportSize({width:1280,height:900});await page.goto(tls.origin+'/t/tenant-a/workspace#/workspace/analysis');await page.reload();await currentCompanion().waitFor();
  });
  await stage('Existing opt-in code-owner PAN diagnostic factory really fails while other modules and same K05 consumer remain usable',async()=>{
   workspace.close();workspace=mountExistingPan549K05WorkspaceV1({source,ksSource,nativeRoot:native.root,gateway:tls.gateway,tenantId:'tenant-a',origin:tls.origin,ownerDiagnosticPlugins:true});receipts.actualDiagnosticCompositionBinding=workspace.binding;await page.goto(tls.origin+'/t/tenant-a/workspace#/workspace/analysis');await page.reload();await currentCompanion().waitFor();assert.equal(await page.getByRole('button',{name:'Fehlende Pflichtabhängigkeit',exact:true}).count(),0);assert.match(await page.locator('body').innerText(),/Fehlende Pflichtabhängigkeit: pan\.missing/);await page.getByRole('button',{name:'Technischer Rendererfehlernachweis',exact:true}).click();await page.getByText('Pluginansicht konnte nicht gerendert werden.',{exact:true}).waitFor();assert.match(await page.locator('body').innerText(),/Pluginfehler/);assert.equal(await page.locator('#ks303-existing-k05-read-companion').count(),0);assert.equal(await page.getByRole('button',{name:'Abmelden',exact:true}).isEnabled(),true);await shot(page,'ks303-desktop-real-owned-plugin-failure');await setup.click();await page.locator('[data-backend="setup"][data-outcome="READBACK_RECEIVED"]').waitFor();await analysis.click();await currentCompanion().waitFor();assert.equal(await page.locator('tr[data-analysis-key="physical"] [data-analysis-value]').innerText(),String(expectedPhysical));assert.deepEqual(rows(),before);record('ACTUAL_ORIGINAL_OWNER_DIAGNOSTIC_PLUGIN_FAILURE_OTHER_MODULE_AND_READCONSUMER_RECOVER');
  });
  await stage('Real expiry clock denies a panel action and retires the prior success without any mutation retry',async()=>{
   const expiresAtMs=Date.now()+4000,expiring=sessions.issueOwnerSession({subjectId:'synthetic:ks303-actual-expiry',role:'reader',expiresAtMs});await cookie(expiring.cookieHeader);await page.goto(tls.origin+'/t/tenant-a/workspace#/workspace/analysis');await page.reload();await currentCompanion().waitFor();await new Promise(r=>setTimeout(r,Math.max(0,expiresAtMs-Date.now()+20)));assert.ok(Date.now()>=expiresAtMs);await page.getByRole('button',{name:'Quell- und Pairidentitäten anzeigen',exact:true}).click();await page.locator('#ks303-existing-k05-read-companion[data-ks303-state="DENIED"]').waitFor();assert.match(await page.locator('#ks303-existing-k05-read-companion').innerText(),/DENIED.*Zugriff verweigert/);assert.equal(await page.locator('[data-backend="analysis"]').getAttribute('data-outcome'),'DENIED');assert.equal(await page.locator('[data-analysis-value],[data-ks303-chart],[data-ks303-panel-contract]').count(),0);assert.equal(await page.evaluate(()=>document.body.dataset.analysisResultRevision??null),null);assert.equal((await request527(tls,'/t/tenant-a/workspace/context',{cookie:expiring.cookieHeader})).status,401);await shot(page,'ks303-desktop-real-expired');await page.setViewportSize({width:390,height:844});await shot(page,'ks303-390-real-expired');assert.deepEqual(rows(),before);record('ACTUAL_CLOCK_EXPIRED_PANEL_USE_DENIED_WITHDRAWN_SUCCESS_NO_MUTATION',{expiresAtMs,TERMINAL_OWN_BINDING_MARKERS_WITHDRAWN:await terminalProof('DENIED')});await cookie(issued.cookieHeader);await page.setViewportSize({width:1280,height:900});await page.goto(tls.origin+'/t/tenant-a/workspace#/workspace/analysis');await page.reload();await currentCompanion().waitFor();
  });
  await stage('Actual protected logout revokes session; subsequent native read denies and never restores cookie or old successful values',async()=>{
   const logout=await request527(tls,'/t/tenant-a/workspace/logout',headers,'POST');assert.equal(logout.status,200);const denied=await request527(tls,'/t/tenant-a/workspace/analysis',httpHeaders,'POST',selector);assert.equal(denied.status,401);assert.equal(denied.headers['set-cookie'],undefined);await setup.click();await analysis.click();await page.locator('[data-backend="analysis"][data-outcome="DENIED"]').waitFor();await terminalProof('DENIED');assert.equal(await page.locator('[data-analysis-value]').count(),0);assert.equal(await page.locator('[data-ks303-chart]').count(),0);await shot(page,'ks303-desktop-real-session-denied');await page.setViewportSize({width:390,height:844});await shot(page,'ks303-390-real-session-denied');assert.deepEqual(rows(),before);record('REAL_NATIVE_LOGOUT_SESSION_REVOKED_BROWSER_DENIED_NO_OLD_VALUES_NO_COOKIE_RENEWAL');
  });
  assert.deepEqual(errors,[]);receipts.actualBrowserVersion=browser.version();receipts.observedRequests=requests;receipts.actualProtectedResults=results;receipts.pageErrors=errors;receipts.allOriginalSourceAndExistingKSBytesRemainQualified=workspace.binding;receipts.visualSighted=false;receipts.sourceEventRowsUnchanged=true;receipts.actualCases=receipts.cases.length;assert.equal(receipts.actualCases,16);
  writeFileSync(join(evidence,'actual-existing-PAN-K05-shared-view-panel-chart-product.json'),JSON.stringify(receipts,null,2)+'\n',{flag:'wx'});
 }catch(error){receipts.failure={name:error.name,message:error.message};if(page){receipts.actualFailureDOM=await page.locator('body').innerText().catch(()=>null);await shot(page,'ks303-actual-failure-diagnostic').catch(()=>{});}writeFileSync(join(evidence,'actual-existing-PAN-K05-shared-view-panel-chart-failure.json'),JSON.stringify(receipts,null,2)+'\n',{flag:'wx'});throw error;}
 finally{await context?.close();await browser?.close();if(fd!==undefined)closeSync(fd);standalone?.close();workspace?.close();native?.close();await tls?.close();process.chdir(oldCwd);}
});
